development:
  adapter: postgresql
  database: twitter_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: twitter_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: twitter_production
  pool: 5
  timeout: 5000